---

- name: Install postgresql (and psycopg2)
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    update_cache: yes
  become: yes
  become_user: root

- name: Create users
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ postgresql_users }}"
  no_log: yes
  become: yes
  become_user: postgres

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: postgres
