---

- name: Install postgresql (and psycopg2)
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    state: latest
    force_apt_get: true
    update_cache: true
    cache_valid_time: 3600
  become: true
  become_user: root

- name: Create users
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ postgresql_users }}"
  no_log: true
  become: true
  become_user: postgres

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
  with_items: "{{ postgresql_databases }}"
  become: true
  become_user: postgres
