---

# name of the app executable and systemd socket / service
web_app_name: ~

# user that the app runs as and uses for its working directory
web_app_user: ~

# ssh authorized (public) key that GitHub Actions will use to deploy the app
# the corresponding private key must be setup as a GH secret: FOOBAR_SSH_KEY
web_app_deployment_key: ~

# list of dicts with keys: name, value
web_app_env_vars: []
