---

- name: restart datomic
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  with_items:
    - datomic-transactor
    - datomic-peer
  become: true
  become_user: root
