---

- name: restart caddy
  systemd:
    name: caddy
    state: reloaded
    daemon_reload: yes
  become: true
  become_user: root

- name: restart web app
  systemd:
    name: "{{ web_app_name }}"
    state: restarted
    daemon_reload: yes
  become: true
  become_user: root
