---

- name: Ensure en_US.UTF-8 locale is available
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: yes
  become_user: root

- name: Check current system locale
  command: localectl status
  register: locale_status
  changed_when: no
  become: yes
  become_user: root

- name: Set system locale
  command: localectl set-locale en_US.UTF-8
  when: "'LANG=en_US.UTF-8' not in locale_status.stdout"
  become: yes
  become_user: root

- name: Install common system tools
  apt:
    name:
      - htop
      - net-tools
      - sqlite3
      - tree
      - unzip
      - vim
    update_cache: yes
  become: yes
  become_user: root

- name: Make vim the default text editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  become: yes
  become_user: root

- name: Disable password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  become: yes
  become_user: root

- name: Limit SSH attempts
  ufw:
    rule: limit
    port: "22"
  become: yes
  become_user: root

- name: Setup firewall rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items: "{{ ubuntu_firewall_rules }}"
  become: yes
  become_user: root

- name: Enable UFW
  ufw:
    state: enabled
  become: yes
  become_user: root
