---

# References:
# https://vincent.bernat.ch/en/blog/2018-systemd-golang-socket-activation
# https://www.darkcoding.net/software/systemd-socket-activation-in-go/

- name: Create the application user
  user:
    name: "{{ go_app_user }}"
    shell: /bin/bash
  become: true
  become_user: root

- name: Setup authorized SSH public key for GitHub Actions
  authorized_key:
    user: "{{ go_app_user }}"
    key: "{{ go_app_deployment_key }}"
  become: true
  become_user: "{{ go_app_user }}"

- name: Create systemd environment vars file
  file:
    path: /home/{{ go_app_user }}/{{ go_app_name }}.env
    state: touch
    mode: "0600"
    modification_time: preserve
    access_time: preserve
  become: true
  become_user: "{{ go_app_user }}"

- name: Setup systemd environment vars
  lineinfile:
    path: /home/{{ go_app_user }}/{{ go_app_name }}.env
    regexp: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
  with_items: "{{ go_app_env_vars }}"
  no_log: true
  become: true
  become_user: "{{ go_app_user }}"

- name: Setup systemd service file
  template:
    src: go.service.j2
    dest: /etc/systemd/system/{{ go_app_name }}.service
    mode: "0644"
  become: true
  become_user: root

- name: Setup systemd socket file
  template:
    src: go.socket.j2
    dest: /etc/systemd/system/{{ go_app_name }}.socket
    mode: "0644"
  become: true
  become_user: root

- name: Allow application user to control the application
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    validate: "visudo -cf %s"
  with_items:
    - "{{ go_app_user }} ALL=NOPASSWD: /bin/systemctl status {{ go_app_name }}"
    - "{{ go_app_user }} ALL=NOPASSWD: /bin/systemctl stop {{ go_app_name }}"
    - "{{ go_app_user }} ALL=NOPASSWD: /bin/systemctl start {{ go_app_name }}"
    - "{{ go_app_user }} ALL=NOPASSWD: /bin/systemctl restart {{ go_app_name }}"
    - "{{ go_app_user }} ALL=NOPASSWD: /bin/systemctl reload {{ go_app_name }}"
  become: true
  become_user: root

- name: Enable systemd unit at startup
  systemd:
    name: "{{ go_app_name }}"
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
