---

- name: Setup Caddy apt repo key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
  become: yes
  become_user: root

- name: Setup Caddy apt repos
  apt_repository:
    repo: "{{ item }}"
    update_cache: no
  with_items:
    - "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
  become: yes
  become_user: root

- name: Install Caddy
  apt:
    name: caddy
    update_cache: yes
  become: yes
  become_user: root

- name: Setup Caddy config file
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0644"
  notify: reload caddy
  become: yes
  become_user: root

# set user password to "*" to allow SSH login
#   with "UsePAM no" in sshd_config
#
# https://arlimus.github.io/articles/usepam/
- name: Create the application user
  user:
    name: "{{ web_app_user }}"
    shell: /bin/bash
    password: "*"
  become: yes
  become_user: root

- name: Setup authorized SSH public key for GitHub Actions
  authorized_key:
    user: "{{ web_app_user }}"
    key: "{{ web_app_deployment_key }}"
  become: yes
  become_user: "{{ web_app_user }}"

- name: Setup systemd environment vars file
  template:
    src: web_app.env.j2
    dest: /home/{{ web_app_user }}/{{ web_app_name }}.env
    mode: "0600"
  notify: restart web app
  no_log: yes
  become: yes
  become_user: root

- name: Setup systemd service file
  template:
    src: web_app.service.j2
    dest: /etc/systemd/system/{{ web_app_name }}.service
    mode: "0644"
  notify: restart web app
  become: yes
  become_user: root

- name: Allow application user to control the application
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    validate: "visudo -cf %s"
  with_items:
    - "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl status {{ web_app_name }}"
    - "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl stop {{ web_app_name }}"
    - "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl start {{ web_app_name }}"
    - "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl restart {{ web_app_name }}"
    - "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl reload {{ web_app_name }}"
  become: yes
  become_user: root

- name: Enable systemd unit at startup
  systemd:
    name: "{{ web_app_name }}"
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
